version: '3'

services:
  main:
    container_name: main
    image: main
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start:dev